from __future__ import annotations
import asyncio
import logging
import random
import re
from datetime import datetime, timezone
from typing import Optional

from sqlalchemy.ext.asyncio import AsyncSession

from app.db.models import Conversation, WhatsAppInstance, WhatsAppMessage
from app.services import pool as instance_pool
from app.services.green_api import build_url
from app.services.rate_limiter import (
    add_footer,
    initial_compose_pause,
    insert_zero_width,
    reply_pause,
    wait_before_send,
)

# ---------------------------------------------------------------------------
# checkWhatsapp cache — avoids hammering the API on every send.
# TTL: 24 hours. Entry: {phone_digits: (exists: bool, checked_at: datetime)}
# ---------------------------------------------------------------------------
_whatsapp_cache: dict[str, tuple[bool, datetime]] = {}
_CACHE_TTL_HOURS = 24

logger = logging.getLogger(__name__)


def _format_phone(phone: str) -> str:
    digits = "".join(c for c in phone if c.isdigit())
    return f"{digits}@c.us"


async def _has_whatsapp(instance: WhatsAppInstance, phone: str) -> bool:
    """
    Return True if the phone number is registered on WhatsApp.
    Results are cached for _CACHE_TTL_HOURS to avoid excessive API calls.
    Fail-open: returns True on network errors so a blip doesn't block sends.
    """
    from app.services.green_api import check_whatsapp
    digits = "".join(c for c in phone if c.isdigit())
    now = datetime.now(timezone.utc)
    cached = _whatsapp_cache.get(digits)
    if cached:
        exists, checked_at = cached
        if (now - checked_at).total_seconds() < _CACHE_TTL_HOURS * 3600:
            return exists
    exists = await check_whatsapp(instance.instance_id, instance.api_token, digits)
    _whatsapp_cache[digits] = (exists, now)
    return exists


async def read_chat(db: AsyncSession, conversation: Conversation) -> bool:
    """Mark a chat as read in Green API. This helps with E2EE sync.

    Uses the same instance that last sent a message to this conversation so the
    read-receipt comes from the correct WhatsApp number.
    """
    from sqlalchemy import select as sa_select
    # Find the instance that last sent to this conversation
    msg_res = await db.execute(
        sa_select(WhatsAppMessage)
        .where(
            WhatsAppMessage.conversation_id == conversation.id,
            WhatsAppMessage.direction == "outbound",
            WhatsAppMessage.instance_id.isnot(None),
        )
        .order_by(WhatsAppMessage.created_at.desc())
        .limit(1)
    )
    last_msg = msg_res.scalar_one_or_none()

    instance: Optional[WhatsAppInstance] = None
    if last_msg and last_msg.instance_id:
        inst_res = await db.execute(
            sa_select(WhatsAppInstance).where(WhatsAppInstance.id == last_msg.instance_id)
        )
        instance = inst_res.scalar_one_or_none()

    # Fall back to any available instance if conversation has no prior outbound message
    if not instance:
        instance = await instance_pool.get_best_instance(db, is_reservation=False)
    if not instance:
        return False

    chat_id = _format_phone(conversation.phone)
    import httpx
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            resp = await client.post(
                build_url(instance.instance_id, instance.api_token, "readChat"),
                json={"chatId": chat_id},
            )
            return resp.status_code == 200
    except Exception as e:
        logger.warning(f"Failed to readChat for {chat_id}: {e}")
        return False


async def send_message(
    db: AsyncSession,
    conversation: Conversation,
    text: str,
    lead_name: Optional[str] = None,
    batch_index: int = 0,
    is_reply: bool = False,
    instance: Optional[WhatsAppInstance] = None,
) -> Optional[WhatsAppMessage]:
    if not instance:
        instance = await instance_pool.get_best_instance(db)

    if not instance:
        logger.error("No available WhatsApp instances in pool")
        return None

    # Keep text as generated by ElevenLabs, add only zero-width uniqueness marker.
    personalized = insert_zero_width(text)

    # Append opt-out footer only for outbound broadcast (not AI replies)
    if not is_reply:
        personalized = add_footer(personalized)

    # Pre-flight: verify the number is on WhatsApp before sending.
    # Avoids noAccount webhook red-flags; result is cached for 24 h.
    if not await _has_whatsapp(instance, conversation.phone):
        from app.services.blacklist import add_to_blacklist
        logger.warning(f"Phone {conversation.phone} has no WhatsApp — blacklisting, skipping send")
        await add_to_blacklist(db, conversation.phone, reason="no_whatsapp")
        return None

    if is_reply:
        # Short human-like typing delay for AI replies.
        await reply_pause()
    else:
        # Wait for per-instance cooldown, then add a compose pause so the first
        # outreach does not fire with bot-like immediacy.
        await wait_before_send(instance)
        await initial_compose_pause()

    chat_id = _format_phone(conversation.phone)
    provider_message_id: Optional[str] = None
    error_text: Optional[str] = None
    status = "failed"

    try:
        provider_message_id, error_text, status = await _do_send(
            instance, chat_id, personalized
        )
    except Exception as e:
        error_text = str(e)
        err_lower = error_text.lower()
        if "banned" in err_lower or "blocked" in err_lower:
            logger.warning(f"Instance {instance.instance_id} appears banned: {e}")
            await instance_pool.mark_banned(db, instance.instance_id)
        else:
            logger.error(f"Send failed for {conversation.phone}: {e}")
    else:
        # Some Green API errors mean the instance is unusable (deleted/invalid).
        if status == "failed" and (error_text or "").lower().find("instance is deleted") != -1:
            logger.warning(f"Instance {instance.instance_id} appears deleted/invalid, disabling it")
            await instance_pool.mark_banned(db, instance.instance_id)

    if status in ("sent", "queued"):
        await instance_pool.record_send(instance.instance_id)

    msg = WhatsAppMessage(
        conversation_id=conversation.id,
        instance_id=instance.id,
        direction="outbound",
        body=personalized,
        provider_message_id=provider_message_id,
        status=status,
        error=error_text,
    )
    db.add(msg)
    await db.commit()
    await db.refresh(msg)

    logger.info(f"Message to {conversation.phone} status={status} id={msg.id}")
    return msg


def split_message(ai_message: str, promo: str, link: str) -> tuple[str, str, str]:
    """Split an AI reply into 3 parts: hook, body, and promo+link.

    Strips the link and promo from the body text so they appear only in part 3.
    Splits on natural sentence boundaries (.!?\\n). Never cuts mid-sentence.
    """
    body = ai_message or ""
    # Strip link and promo from body so they land exclusively in part 3
    if link:
        body = body.replace(link, "")
    if promo:
        body = body.replace(promo, "")
    # Clean up leftover blank lines and whitespace
    body = re.sub(r"\n{2,}", "\n", body).strip()

    # Split into sentences at . ! ? or newline boundaries
    sentences = [s.strip() for s in re.split(r"(?<=[.!?])\s+|\n", body) if s.strip()]
    if not sentences:
        sentences = [body] if body else [""]

    if len(sentences) == 1:
        part1 = sentences[0]
        part2 = sentences[0]
    elif len(sentences) == 2:
        part1, part2 = sentences[0], sentences[1]
    else:
        part1 = sentences[0]
        part2 = " ".join(sentences[1:])

    # Part 3 — promo code + link (one per line); fall back to repeating part2
    part3_lines = [x for x in [promo, link] if x]
    part3 = "\n".join(part3_lines) if part3_lines else part2

    return part1, part2, part3


async def send_split_message(
    db: AsyncSession,
    conversation: Conversation,
    ai_message: str,
    promo: str,
    link: str,
    is_cold: bool = False,
) -> None:
    """Send an AI reply as 3 separate messages with typing indicators and human-like delays.

    Part 1 = greeting/hook, Part 2 = body, Part 3 = promo + link.
    Uses shorter inter-part pauses for warm replies and longer ones for cold outreach.
    Wraps everything in try/except so the webhook always returns 200.
    """
    import httpx

    try:
        instance = await instance_pool.get_best_instance(db)
        if not instance:
            logger.error("No available WhatsApp instances for send_split_message")
            return

        chat_id = _format_phone(conversation.phone)
        parts = list(split_message(ai_message, promo, link))
        typing_multiplier = 1.5 if is_cold else 1.0
        send_status = "failed"

        for i, part in enumerate(parts):
            if not part:
                continue

            # 1. Typing indicator
            typing_secs = max(3.0, min(10.0, len(part) * 0.05)) * typing_multiplier
            typing_url = build_url(instance.instance_id, instance.api_token, "sendTyping")
            try:
                async with httpx.AsyncClient(timeout=10.0) as client:
                    await client.post(
                        typing_url,
                        json={"chatId": chat_id, "typingTime": int(typing_secs)},
                    )
            except Exception as e:
                logger.warning(f"Typing indicator failed for part {i + 1}: {e}")

            # 2. Emulate typing duration
            await asyncio.sleep(typing_secs)

            # 3. Send the part
            text_to_send = insert_zero_width(part)
            provider_id = None
            error_text = None
            send_status = "failed"
            try:
                provider_id, error_text, send_status = await _do_send(instance, chat_id, text_to_send)
            except Exception as e:
                logger.error(f"send_split_message part {i + 1}/3 failed for {conversation.phone}: {e}")

            # 4. Persist to DB
            msg = WhatsAppMessage(
                conversation_id=conversation.id,
                instance_id=instance.id,
                direction="outbound",
                body=text_to_send,
                provider_message_id=provider_id,
                status=send_status,
                error=error_text,
            )
            db.add(msg)
            await db.commit()
            logger.info(f"Sent part {i + 1}/3 to {chat_id} status={send_status}")

            # 5. Inter-part pause (skip after last part)
            if i < len(parts) - 1:
                pause = random.uniform(15, 35) if is_cold else random.uniform(8, 20)
                await asyncio.sleep(pause)

        if send_status in ("sent", "queued"):
            await instance_pool.record_send(instance.instance_id)

    except Exception as e:
        logger.error(f"send_split_message unexpected error for {conversation.phone}: {e}")


def calc_typing_time(message: str) -> int:
    # Delegates to rate_limiter to keep logic in one place
    from app.services.rate_limiter import calc_typing_time as _calc
    return _calc(message)


async def _do_send(
    instance: WhatsAppInstance,
    chat_id: str,
    text: str,
) -> tuple[Optional[str], Optional[str], str]:
    """Send typing indicator, wait, then send message via Green API. Returns (provider_id, error, status)."""
    import httpx
    import asyncio

    # Send "typing..." indicator first
    typing_ms = calc_typing_time(text)
    typing_payload = {
        "chatId": chat_id,
        "typingTime": max(1, typing_ms // 1000),  # Green API expects seconds
    }
    typing_url = build_url(instance.instance_id, instance.api_token, "sendTyping")
    url = build_url(instance.instance_id, instance.api_token, "sendMessage")
    payload = {
        "chatId": chat_id,
        "message": text,
        "linkPreview": False,
    }
    # 1. Fire typing indicator (separate client — don't hold connection during sleep)
    try:
        async with httpx.AsyncClient(timeout=15.0) as client:
            await client.post(typing_url, json=typing_payload)
    except Exception as e:
        logger.warning(f"Failed to send typing indicator: {e}")

    # 2. Emulate typing duration — outside any open HTTP client
    await asyncio.sleep(typing_ms / 1000.0)

    # 3. Actually send the message
    async with httpx.AsyncClient(timeout=30.0) as client:
        resp = await client.post(url, json=payload)

    if resp.status_code in (403, 429):
        # Trigger an immediate health check in the background so the monitor
        # updates the instance state without waiting for the next 60-second cycle.
        asyncio.create_task(_async_health_check(instance))
        raise RuntimeError(f"HTTP {resp.status_code} from Green API — likely banned/rate-limited")

    data = {}
    try:
        data = resp.json()
    except Exception:
        pass

    if resp.status_code != 200:
        raw = ""
        try:
            raw = resp.text
        except Exception:
            raw = ""
        error = data.get("message") or data.get("error") or (raw.strip() if raw else f"HTTP {resp.status_code}")
        logger.warning(
            "Green API sendMessage failed: status=%s instance_id=%s chat_id=%s body=%s",
            resp.status_code,
            instance.instance_id,
            chat_id,
            (raw[:500] if raw else data),
        )
        return None, error, "failed"

    provider_id = data.get("idMessage")
    if provider_id:
        logger.info(f"Green API: message sent, provider_id={provider_id}")
    return provider_id, None, "sent"


async def _async_health_check(instance: WhatsAppInstance) -> None:
    """Fire-and-forget: check instance state immediately and update DB."""
    try:
        from app.services.health_monitor import check_instance
        await check_instance(instance)
    except Exception as e:
        logger.warning(f"Immediate health check for {instance.instance_id} failed: {e}")


async def send_initial_message(
    db: AsyncSession,
    conversation: Conversation,
    initial_text: str | list[str],
    batch_index: int = 0,
    is_cold: bool = True,
) -> Optional[WhatsAppMessage]:
    messages = [initial_text] if isinstance(initial_text, str) else initial_text
    last_msg = None
    selected_instance = None

    for i, text in enumerate(messages):
        # 1st message: selects and reserves instance (4 min cooldown)
        # Subsequent: reuses same instance with short typing delay
        is_seq = i > 0

        msg = await send_message(
            db=db,
            conversation=conversation,
            text=text,
            lead_name=conversation.lead_name,
            batch_index=batch_index,
            is_reply=is_seq,
            instance=selected_instance,
        )
        if i == 0:
            last_msg = msg
            # Record first_contact_at on the first successful cold send
            if msg and conversation.first_contact_at is None:
                conversation.first_contact_at = datetime.now(timezone.utc)
                await db.commit()

        # Track outbound stats for conversion funnel
        if msg and msg.status in ("sent", "queued"):
            # Refresh to get latest DB state (object may be expired after prior commit)
            await db.refresh(conversation)
            now_utc = datetime.now(timezone.utc)
            conversation.outbound_count = (conversation.outbound_count or 0) + 1
            conversation.last_activity_at = now_utc
            if conversation.lead_status in ("new", None):
                conversation.lead_status = "contacted"
                # Log lead_event for first contact
                if i == 0:
                    from app.db.models import LeadEvent
                    db.add(LeadEvent(
                        conversation_id=conversation.id,
                        event_type="contacted",
                        note=f"Initial outreach sent (part {i + 1})",
                    ))
            db.add(conversation)
            await db.commit()
            if msg and msg.instance_id:
                from sqlalchemy import select
                res = await db.execute(
                    select(WhatsAppInstance).where(WhatsAppInstance.id == msg.instance_id)
                )
                selected_instance = res.scalar_one_or_none()
                if not selected_instance:
                    logger.warning(
                        "Instance disappeared after first send for %s; subsequent parts will pick a new one",
                        conversation.phone,
                    )

        # Wait before the next part of a multi-part message
        if i < len(messages) - 1:
            if is_cold:
                await asyncio.sleep(random.uniform(15, 35))
            else:
                await reply_pause(min_sec=8.0, max_sec=16.0)

    return last_msg
