import logging
from datetime import datetime, timezone
from typing import Optional

from sqlalchemy.ext.asyncio import AsyncSession

from app.db.models import Conversation, WhatsAppInstance, WhatsAppMessage
from app.services import pool as instance_pool
from app.services.green_api import build_url
from app.services.rate_limiter import add_footer, insert_zero_width, reply_pause, wait_before_send

# ---------------------------------------------------------------------------
# checkWhatsapp cache — avoids hammering the API on every send.
# TTL: 24 hours. Entry: {phone_digits: (exists: bool, checked_at: datetime)}
# ---------------------------------------------------------------------------
_whatsapp_cache: dict[str, tuple[bool, datetime]] = {}
_CACHE_TTL_HOURS = 24

logger = logging.getLogger(__name__)


def _format_phone(phone: str) -> str:
    digits = "".join(c for c in phone if c.isdigit())
    return f"{digits}@c.us"


async def _has_whatsapp(instance: WhatsAppInstance, phone: str) -> bool:
    """
    Return True if the phone number is registered on WhatsApp.
    Results are cached for _CACHE_TTL_HOURS to avoid excessive API calls.
    Fail-open: returns True on network errors so a blip doesn't block sends.
    """
    from app.services.green_api import check_whatsapp
    digits = "".join(c for c in phone if c.isdigit())
    now = datetime.now(timezone.utc)
    cached = _whatsapp_cache.get(digits)
    if cached:
        exists, checked_at = cached
        if (now - checked_at).total_seconds() < _CACHE_TTL_HOURS * 3600:
            return exists
    exists = await check_whatsapp(instance.instance_id, instance.api_token, digits)
    _whatsapp_cache[digits] = (exists, now)
    return exists


async def read_chat(db: AsyncSession, conversation: Conversation) -> bool:
    """Mark a chat as read in Green API. This helps with E2EE sync.

    Uses the same instance that last sent a message to this conversation so the
    read-receipt comes from the correct WhatsApp number.
    """
    from sqlalchemy import select as sa_select
    # Find the instance that last sent to this conversation
    msg_res = await db.execute(
        sa_select(WhatsAppMessage)
        .where(
            WhatsAppMessage.conversation_id == conversation.id,
            WhatsAppMessage.direction == "outbound",
            WhatsAppMessage.instance_id.isnot(None),
        )
        .order_by(WhatsAppMessage.created_at.desc())
        .limit(1)
    )
    last_msg = msg_res.scalar_one_or_none()

    instance: Optional[WhatsAppInstance] = None
    if last_msg and last_msg.instance_id:
        inst_res = await db.execute(
            sa_select(WhatsAppInstance).where(WhatsAppInstance.id == last_msg.instance_id)
        )
        instance = inst_res.scalar_one_or_none()

    # Fall back to any available instance if conversation has no prior outbound message
    if not instance:
        instance = await instance_pool.get_best_instance(db, is_reservation=False)
    if not instance:
        return False

    chat_id = _format_phone(conversation.phone)
    import httpx
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            resp = await client.post(
                build_url(instance.instance_id, instance.api_token, "readChat"),
                json={"chatId": chat_id},
            )
            return resp.status_code == 200
    except Exception as e:
        logger.warning(f"Failed to readChat for {chat_id}: {e}")
        return False


async def send_message(
    db: AsyncSession,
    conversation: Conversation,
    text: str,
    lead_name: Optional[str] = None,
    batch_index: int = 0,
    is_reply: bool = False,
    instance: Optional[WhatsAppInstance] = None,
) -> Optional[WhatsAppMessage]:
    if not instance:
        instance = await instance_pool.get_best_instance(db)

    if not instance:
        logger.error("No available WhatsApp instances in pool")
        return None

    # Keep text as generated by ElevenLabs, add only zero-width uniqueness marker.
    personalized = insert_zero_width(text)

    # Append opt-out footer only for outbound broadcast (not AI replies)
    if not is_reply:
        personalized = add_footer(personalized)

    # Pre-flight: verify the number is on WhatsApp before sending.
    # Avoids noAccount webhook red-flags; result is cached for 24 h.
    if not await _has_whatsapp(instance, conversation.phone):
        from app.services.blacklist import add_to_blacklist
        logger.warning(f"Phone {conversation.phone} has no WhatsApp — blacklisting, skipping send")
        await add_to_blacklist(db, conversation.phone, reason="no_whatsapp")
        return None

    if is_reply:
        # Short human-like typing delay for AI replies (2–5s)
        await reply_pause()
    else:
        # Wait for per-instance cooldown; batch_pause is now the caller's responsibility
        await wait_before_send(instance)

    chat_id = _format_phone(conversation.phone)
    provider_message_id: Optional[str] = None
    error_text: Optional[str] = None
    status = "failed"

    try:
        provider_message_id, error_text, status = await _do_send(
            instance, chat_id, personalized
        )
    except Exception as e:
        error_text = str(e)
        err_lower = error_text.lower()
        if "banned" in err_lower or "blocked" in err_lower:
            logger.warning(f"Instance {instance.instance_id} appears banned: {e}")
            await instance_pool.mark_banned(db, instance.instance_id)
        else:
            logger.error(f"Send failed for {conversation.phone}: {e}")
    else:
        # Some Green API errors mean the instance is unusable (deleted/invalid).
        if status == "failed" and (error_text or "").lower().find("instance is deleted") != -1:
            logger.warning(f"Instance {instance.instance_id} appears deleted/invalid, disabling it")
            await instance_pool.mark_banned(db, instance.instance_id)

    if status in ("sent", "queued"):
        await instance_pool.record_send(instance.instance_id)

    msg = WhatsAppMessage(
        conversation_id=conversation.id,
        instance_id=instance.id,
        direction="outbound",
        body=personalized,
        provider_message_id=provider_message_id,
        status=status,
        error=error_text,
    )
    db.add(msg)
    await db.commit()
    await db.refresh(msg)

    logger.info(f"Message to {conversation.phone} status={status} id={msg.id}")
    return msg


def calc_typing_time(message: str) -> int:
    # Delegates to rate_limiter to keep logic in one place
    from app.services.rate_limiter import calc_typing_time as _calc
    return _calc(message)


async def _do_send(
    instance: WhatsAppInstance,
    chat_id: str,
    text: str,
) -> tuple[Optional[str], Optional[str], str]:
    """Send typing indicator, wait, then send message via Green API. Returns (provider_id, error, status)."""
    import httpx
    import asyncio

    # Send "typing..." indicator first
    typing_ms = calc_typing_time(text)
    typing_payload = {
        "chatId": chat_id,
        "typingTime": max(1, typing_ms // 1000),  # Green API expects seconds
    }
    typing_url = build_url(instance.instance_id, instance.api_token, "sendTyping")
    url = build_url(instance.instance_id, instance.api_token, "sendMessage")
    payload = {
        "chatId": chat_id,
        "message": text,
        "linkPreview": False,
    }
    # 1. Fire typing indicator (separate client — don't hold connection during sleep)
    try:
        async with httpx.AsyncClient(timeout=15.0) as client:
            await client.post(typing_url, json=typing_payload)
    except Exception as e:
        logger.warning(f"Failed to send typing indicator: {e}")

    # 2. Emulate typing duration — outside any open HTTP client
    await asyncio.sleep(typing_ms / 1000.0)

    # 3. Actually send the message
    async with httpx.AsyncClient(timeout=30.0) as client:
        resp = await client.post(url, json=payload)

    if resp.status_code in (403, 429):
        # Trigger an immediate health check in the background so the monitor
        # updates the instance state without waiting for the next 60-second cycle.
        asyncio.create_task(_async_health_check(instance))
        raise RuntimeError(f"HTTP {resp.status_code} from Green API — likely banned/rate-limited")

    data = {}
    try:
        data = resp.json()
    except Exception:
        pass

    if resp.status_code != 200:
        raw = ""
        try:
            raw = resp.text
        except Exception:
            raw = ""
        error = data.get("message") or data.get("error") or (raw.strip() if raw else f"HTTP {resp.status_code}")
        logger.warning(
            "Green API sendMessage failed: status=%s instance_id=%s chat_id=%s body=%s",
            resp.status_code,
            instance.instance_id,
            chat_id,
            (raw[:500] if raw else data),
        )
        return None, error, "failed"

    provider_id = data.get("idMessage")
    if provider_id:
        logger.info(f"Green API: message sent, provider_id={provider_id}")
    return provider_id, None, "sent"


async def _async_health_check(instance: WhatsAppInstance) -> None:
    """Fire-and-forget: check instance state immediately and update DB."""
    try:
        from app.services.health_monitor import check_instance
        await check_instance(instance)
    except Exception as e:
        logger.warning(f"Immediate health check for {instance.instance_id} failed: {e}")


async def send_initial_message(
    db: AsyncSession,
    conversation: Conversation,
    initial_text: str | list[str],
    batch_index: int = 0,
) -> Optional[WhatsAppMessage]:
    messages = [initial_text] if isinstance(initial_text, str) else initial_text
    last_msg = None
    selected_instance = None

    for i, text in enumerate(messages):
        # 1st message: selects and reserves instance (4 min cooldown)
        # Subsequent: reuses same instance with short typing delay
        is_seq = i > 0

        msg = await send_message(
            db=db,
            conversation=conversation,
            text=text,
            lead_name=conversation.lead_name,
            batch_index=batch_index,
            is_reply=is_seq,
            instance=selected_instance,
        )
        if i == 0:
            last_msg = msg
            if msg and msg.instance_id:
                from sqlalchemy import select
                res = await db.execute(
                    select(WhatsAppInstance).where(WhatsAppInstance.id == msg.instance_id)
                )
                selected_instance = res.scalar_one_or_none()
                if not selected_instance:
                    logger.warning(
                        "Instance disappeared after first send for %s; subsequent parts will pick a new one",
                        conversation.phone,
                    )

        # Wait before the next part of a multi-part message
        if i < len(messages) - 1:
            await reply_pause(min_sec=3.0, max_sec=6.0)

    return last_msg
